// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models;

namespace Web.Migrations
{
    [DbContext(typeof(DrugContext))]
    [Migration("20200803121311_AddDrugStore")]
    partial class AddDrugStore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Medtronic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cardinal Health"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Abbott"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Baxter "
                        },
                        new
                        {
                            Id = 5,
                            Name = "Romfarm "
                        });
                });

            modelBuilder.Entity("Web.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdverseReactions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicalPharmacology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeATX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Composition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraindications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dependence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowSupplied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NonProprietaryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overdosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacotherapeuticGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PharmacotherapeuticProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precautions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tradename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UmageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 5,
                            Tradename = "Slezin"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Tradename = "Almagel"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            Tradename = "Colchicine"
                        });
                });

            modelBuilder.Entity("Web.Views.DrugStore.DrugItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int?>("DrugStoreId")
                        .HasColumnType("int");

                    b.Property<int>("IsRecipeNeeded")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DrugId");

                    b.HasIndex("DrugStoreId");

                    b.ToTable("DrugItem");
                });

            modelBuilder.Entity("Web.Views.DrugStore.DrugStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("DrugStores");
                });

            modelBuilder.Entity("Web.Models.Drug", b =>
                {
                    b.HasOne("Web.Models.Company", "Company")
                        .WithMany("Drugs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Web.Views.DrugStore.DrugItem", b =>
                {
                    b.HasOne("Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Models.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Views.DrugStore.DrugStore", null)
                        .WithMany("DrugItems")
                        .HasForeignKey("DrugStoreId");
                });
#pragma warning restore 612, 618
        }
    }
}
